#! /bin/sh
# █▀▀▄ █▀▀ █▀▀█ █░░░█ █▀▄▀█ █▀▀█ █▀▀
# █▀▀▄ ▀▀█ █░░█ █▄█▄█ █░▀░█ █▄▄▀ █░░
# ▀▀▀░ ▀▀▀ █▀▀▀ ░▀░▀░ ▀░░░▀ ▀░▀▀ ▀▀▀
#####################################
# Make sure sxhkd is always running
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Reload sxhkd after run bspwm
# pkill sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

### Monitor
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
	bspc monitor $m -d 1 2 3 4 5 6
done

xresource() {
	xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

###Config
# window
bspc config border_width              1
bspc config top_padding               32
bspc config right_padding             0
bspc config left_padding              0
bspc config bottom_padding            0
bspc config window_gap                4
bspc config top_monocle_padding       0
bspc config right_monocle_padding     0
bspc config left_monocle_padding      0
bspc config bottom_monocle_padding    0

# monitor
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors  true

# border
bspc config focused_border_color  $(xresource color4)
bspc config normal_border_color   $(xresource color0)
bspc config active_border_color   $(xresource color8)
bspc config borderless_monocle     false

bspc config split_ratio            0.50
bspc config gapless_monocle        false
bspc config focus_follows_pointer  true
bspc config presel_feedback_color  $(xresource color4)

###Rules
# Cleanup
bspc rule -r '*'

# State rules
bspc rule -a "Thunar"              state=floating
bspc rule -a "Yad"                 state=floating
bspc rule -a "Iwgtk"               state=floating
bspc rule -a "feh"                 state=floating
bspc rule -a "Arandr"              state=floating
bspc rule -a "Worklog Assistant"   state=floating

# Assignment rules
bspc rule -a "Chromium"            desktop=^1 follow=on
bspc rule -a "Ptask"               desktop=^2 follow=on
bspc rule -a "code-oss"            desktop=^4 follow=on
bspc rule -a "Slack"               desktop=^3 follow=on
# bspc rule -a "TelegramDesktop"     desktop=^3 follow=on
bspc rule -a "discord"             desktop=^3 follow=on

bspc config external_rules_command "$SCRIPTPATH/external_rules"

wmname LG3D
### Non-bspwm specific settings
# xset s 0 0
# xset dpms 0 0 0
# (sleep 10; xset r rate 440 50) & #Doesnt work imediately at startup for some odd reason. The other xset commands seem fine
# xsetroot -cursor_name left_ptr &
#xset +fp ~/.fonts/misc/

###Application startup
~/.fehbg &
~/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xsetroot -cursor_name left_ptr &
xrdb -load ~/.Xresources &
